### PR TITLE
feat(preflight): add detail warning message when validating preflight and host preflight spec

### LINKED ISSUE #227: kind: Preflight with no analyzers shows a misleading error
With Preflight 0.38, if I run preflight checks and don't include an analyzers section, the error message is:

```
  Running Preflight checks ⠴ Error: no data has been collected
```

If Preflights require analyzers, the message should show that. If we can have a better experience with no analyzers, that's even better.

### PR DESCRIPTION
**Pull request by DexterYan**
## Description, Motivation and Context

- add validate_spec.go in preflight to validate if the preflight or host preflight spec is meaningful
- return warning messages without throwing errors which stops the workflow
- add extra tests for  preflight  and host preflight specs yaml

Fixes: #227

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by DexterYan** [comment]
## No Analyzers
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_empty_analyzers_gotest.yaml
Warning: No analyzers found
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - clusterInfo: {}
  analyzers: []
```

## No Host Preflight anazlyers
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_host_preflight_validate_empty_analyzers_gotest.yaml
Warning: No analyzers found
```

## Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: sample
spec:
  collectors:
    - cpu: {}
  analyzers: []
```

**Comment by DexterYan** [comment]
## No Host collectors
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_host_preflight_validate_empty_collectors_gotest.yaml
Warning: No collectors found
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: sample
spec:
  analyzers:
    - hostOS:
        outcomes:
          - fail:
              when: "ubuntu-16.04-kernel < 4.15"
              message: unsupported distribution
          - pass:
              when: "ubuntu-18.04-kernel >= 4.15"
              message: supported distribution

```

**Comment by DexterYan** [comment]
## All Default Collectors Excluded
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_all_default_collectors_gotest.yaml
Warning: All collectors were excluded by the applied values
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - clusterInfo: 
        exclude: true
    - clusterResources: 
        exclude: true
  analyzers:
    - clusterVersion:
        outcomes:
        - pass:
            message: Cluster is up to date
```

## One Default Collector Excluded
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_one_default_collectors_gotest.yaml
Running Preflight Checks 
```

## Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - clusterInfo: 
        exclude: true
  analyzers:
    - clusterVersion:
        outcomes:
        - pass:
            message: Cluster is up to date
```

## All Non Default Collector Excluded
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_all_non_default_collectors_gotest.yaml
Running Preflight Checks 
```

## Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - http:
        exclude: true
        name: healthz
        get:
          url: http://api:3000/healthz
    - data:
        exclude: true
        collectorName: my-password-dump
        name: data
        data: |
          my super secret password is abc123
          another redaction will go here
  analyzers:
    - distribution:
        outcomes:
          - pass:
              when: "== k3s"
              message: K3S is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - clusterVersion:
        outcomes:
        - pass:
            message: Cluster is up to date
```

**Comment by DexterYan** [comment]
## All analyzers are excluded
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_analyzers_gotest.yaml
Warning: All analyzers were excluded by the applied values
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - distribution:
        exclude: true
        outcomes:
          - pass:
              when: "== k3s"
              message: K3S is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - clusterVersion:
        exclude: true
        outcomes:
        - pass:
            message: Cluster is up to date
```

**Comment by DexterYan** [comment]
## No Spec
create a no spec helm chat
```
helm template oci://registry.replicated.com/dexter-yan-test/unstable/dexter-app | ./bin/preflight -          
Pulled: registry.replicated.com/dexter-yan-test/unstable/dexter-app:0.1.3
Digest: sha256:2c0428e786869541c509189611ad1523eea6d68fea89cfe409e8cb58ae6f634b
Warning: no preflight or host preflight spec was found
```

**Review by CpuID — APPROVED** [review]
glanced over the code, LGTM no red flags. and the test coverage looks fairly comprehensive and it's passing, which is my main metric of success here 👍 

I did see there's some use of `reflect`, was a bit worried about that at first but I can see we've used it elsewhere in troubleshoot, so not a big deal.

**Pull request merged**
