### PR TITLE
feat(e2e): add e2e go test for cluster resource

### PR DESCRIPTION
**Pull request by DexterYan**
## Description, Motivation and Context

- use e2e-framework to package our current bash e2e tests into go test
- change github action to support e2e test
- add test for cluster resource collector and pod status

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by CpuID** [comment]
Interesting 👍 

Not sure if I'd want to completely remove the standalone binary e2e test just yet, but as an additional test there's some valid use cases for sure.

**Comment by banjoh** [comment]
I like this framework and how it approaches end-to-end testing especially cause
* It exposes `testing.T` tests and hence uses `go test` harness.
* It has traditional/xUnit type `SetUp/TearDown` functions which help see the environment the tests run within the same code base

Out of curiosity, have you considered other alternatives? 

As we look to introducing a new testing framework, we need to evaluate the following backlog issues to see whether we address their goals.

* https://github.com/replicatedhq/troubleshoot/issues/962
* https://github.com/replicatedhq/troubleshoot/issues/1225
* https://github.com/replicatedhq/troubleshoot/issues/891
* ...

IMO, this should lead to an ADR given that it might lead to using different tools/frameworks and different approach to testing.

**Comment by DexterYan** [comment]
@banjoh, I checked other k8s test framework, seems not good e2e test like this one.

Currently, it worked in GitHub [action](https://github.com/replicatedhq/troubleshoot/actions/runs/5946802820/job/16127956874?pr=1265). So it should be suitable for Windows testing.

**Review by CpuID — DISMISSED** [review]
this looks pretty good to me 👍 adds more tests than we had before, and they pass :)

**Comment by DexterYan** [comment]
Thank you @CpuID. I have added one more case to check the pending pod status. 

In go e2e test, we can directly import **github.com/replicatedhq/troubleshoot/pkg/convert** as convert.Result to read our analysis.json. It seems more efficient then current bash way.

**Review by CpuID — APPROVED** [review]

**Pull request merged**
