### PR TITLE
Add collection of roles, cluster roles and their bindings

### LINKED ISSUE #778: Collect RBAC resources as part of support bundle.
Hi there,
There is currently no collection of RBAC resources, namely `Roles`, `RoleBindings`, `ClusterRoles` and `ClusterRoleBindings`, deployed on the k8s cluster using troubleshoot.sh This feature would be nice to have since the roles and their bindings are integral to cluster activities and applications.

### PR DESCRIPTION
**Pull request by ahmedElqutb**
resolves: [#778](https://github.com/replicatedhq/troubleshoot/issues/778)

## Overview

Added collection for the namespaced resources `Roles` and `RoleBindings` and the non-namespaced resources `ClusterRoles` and the `ClusterRolesBindings`, once collected it looks something like this:
```
support-bundle-YYYY-mm-ddTHH_ii_ss
├── cluster-resources/
│   └── roles/
│   └── rolebindings/
│   └── clusterroles.json
│   └── clusterrolebindings.json
```
Testing
The changes are tested manually by creating the support bundle from the KIND cluster having some from the resources in question deployed.
Co-authored-by: Martin Hrabovcin(@mhrabovcin) [mhrabovcin@users.noreply.github.com](mailto:mhrabovcin@users.noreply.github.com)

### CODE REVIEW

**Review by edgarlanting — COMMENTED** [review]
Thank you @ahmedElqutb @mhrabovcin for this PR! We just need Ahmed to sign the CLA before we can approve the PR

**Comment by ahmedElqutb** [comment]
> Thank you @ahmedElqutb @mhrabovcin for this PR! We just need Ahmed to sign the CLA before we can approve the PR

Hi @edgarlanting, was a mixup on my side now all should be fine. thanks!

**Comment by edgarlanting** [comment]
Hi @ahmedElqutb & @mhrabovcin I've just reviewed and approved the PR, thanks a lot for your contribution!

**Review by edgarlanting — APPROVED** [review]
LGTM! Thanks for the PR and the contribution to Troubleshoot!
-Edgar

**Review by divolgin — APPROVED** [review]

**Pull request merged**
