### PR TITLE
Longhorn.go 287 issue

### PR DESCRIPTION
**Pull request by drohnow**
## Description, Motivation and Context

Please include a summary of the change or what problem it solves. Please also include relevant motivation and context.

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by banjoh** [comment]
Quite a lot of changes here. Was this PR branched off the main branch?

**Comment by drohnow** [comment]
See slack message on this. Go ahead and discard this PR.Sent from my iPhoneOn Feb 22, 2023, at 3:59 AM, Evans Mungai ***@***.***> wrote:﻿
Quite a lot of changes here. Was this PR branched off the main branch?

**Comment by banjoh** [comment]
OK. I'll wait for right PRs

**Comment by drohnow** [comment]
closing this PR and will open a new PR shortly.

**Pull request closed without merging**
