### PR TITLE
feat(analyzer): add detailed message for unhealthy pod

### PR DESCRIPTION
**Pull request by DexterYan**
## Description, Motivation and Context

- add event message from unhealthy pod
- if the pod is crashing, it will return the last terminated pod messages
- if the pod is crashing and no terminated pod messages, it will return exit code
- if the pod is crashing with initial container, it will check events and return the warning messages
- the clusterPodStatuses will check both events and pod status to find all the useful messages or exit code

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by DexterYan** [comment]
### Spec Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources: {}
    - clusterInfo: {}
  analyzers:
    - clusterPodStatuses:
        checkName: "Pod(s) health status(es)"
        outcomes:
          - fail:
              title: "Pod {{ .Name }} is unable to pull images"
              when: "== ImagePullBackOff"
              message: "A Pod, {{ .Name }}, is unable to pull its image. Status is: {{ .Status.Reason }}"
          - warn:
              title: "Pod {{ .Name }} is unhealthy"
              when: "!= Healthy"
              message: "A Pod, {{ .Name }}, is unhealthy with a status of: {{ .Status.Reason }} with message of {{ .Status.Message }}"
          - pass:
              title: "Pod {{ .Name }} is healthy"
              message: "Pod {{ .Name }} is healthy"

```

### Situation
```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  20m (x14 over 6h2m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

### Result
```
        {
            "name": "pod.s.health.status.es.",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "pod.s.health.status.es.",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Pod(s) health status(es)",
                "detail": "A Pod, kotsadm-65f9f84c66-9675f, is unhealthy with a status of: Pending with message of 0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": "",
            "involvedObject": {
                "kind": "Pod",
                "namespace": "test",
                "name": "kotsadm-65f9f84c66-9675f",
                "apiVersion": "v1"
            }
        },
```

**Comment by CpuID** [comment]
Possible idea: for pods in a crash loop, expose the exit code of the container that ended?

**Comment by DexterYan** [comment]
### pod crashloop backoff

```
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    command:
      - wge
      - "-O"
      - "/work-dir/index.html"
      - https://home.robusta.dev

```

### result
```
{
            "name": "pod.s.health.status.es.",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "pod.s.health.status.es.",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Pod(s) health status(es)",
                "detail": "A Pod, init-demo, is unhealthy with a status of: CrashLoopBackOff. Message is: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"wge\": executable file not found in $PATH: unknown",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": "",
            "involvedObject": {
                "kind": "Pod",
                "namespace": "default",
                "name": "init-demo",
                "apiVersion": "v1"
            }
        }
```

**Comment by DexterYan** [comment]
### initial pod crashloop backoff
```
apiVersion: v1
kind: Pod
metadata:
  name: init-demo2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wge
    - "-O"
    - "/work-dir/index.html"
    - https://home.robusta.dev
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}

```
### result
```
{
            "name": "pod.s.health.status.es.",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "pod.s.health.status.es.",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Pod(s) health status(es)",
                "detail": "A Pod, init-demo2, is unhealthy with a status of: Init:RunContainerError. Message is: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"wge\": executable file not found in $PATH: unknown",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": "",
            "involvedObject": {
                "kind": "Pod",
                "namespace": "default",
                "name": "init-demo2",
                "apiVersion": "v1"
            }
        }
```

**Comment by DexterYan** [comment]
### pending pod resources
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-pod-resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pending-pod-resources
  template:
    metadata:
      labels:
        app: pending-pod-resources
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            nvidia.com/gpu: 5
            cpu: 3
            memory: 5Gi
          limits:
            nvidia.com/gpu: 5
            cpu: 3
            memory: 5Gi

```

### result
```
{
            "name": "pod.s.health.status.es.",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "pod.s.health.status.es.",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Pod(s) health status(es)",
                "detail": "A Pod, pending-pod-resources-5fddcf7688-djjfc, is unhealthy with a status of: Pending. Message is: 0/1 nodes are available: 1 Insufficient nvidia.com/gpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": "",
            "involvedObject": {
                "kind": "Pod",
                "namespace": "default",
                "name": "pending-pod-resources-5fddcf7688-djjfc",
                "apiVersion": "v1"
            }
        }
```

**Comment by DexterYan** [comment]
### oomkill pod
```
apiVersion: batch/v1
kind: Job
metadata:
  name: oom-kill-job3
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - 75Mi
        - "0"
        - 30Mi
        - "80"
        - "1"
        image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/memory-eater:1.0
        imagePullPolicy: Always
        name: memory-eater
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
      restartPolicy: Never

```

### result
```
{
            "name": "pod.s.health.status.es.",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "pod.s.health.status.es.",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Pod(s) health status(es)",
                "detail": "A Pod, oom-kill-job3-gbb89, is unhealthy with a status of: OOMKilled. Message is: ExitCode:137",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": "",
            "involvedObject": {
                "kind": "Pod",
                "namespace": "default",
                "name": "oom-kill-job3-gbb89",
                "apiVersion": "v1"
            }
        }
```

**Comment by DexterYan** [comment]
### image pull fail
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-image-deployment
  labels:
    app.kubernetes.io/name: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-image-deployment
  template:
    metadata:
      labels:
        app: no-image-deployment
        visualize: "true"
    spec:
      containers:
        - name: demo-deployment-container
          image: noimage.com/no-such-image
          imagePullPolicy: IfNotPresent

```

### result
```
{
            "name": "pod.s.health.status.es.",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "pod.s.health.status.es.",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Pod(s) health status(es)",
                "detail": "A Pod, no-image-deployment-849c4c4958-rxqmt, is unhealthy with a status of: ErrImagePull. Message is: Failed to pull image \"noimage.com/no-such-image\": rpc error: code = Unknown desc = Error response from daemon: Get \"https://noimage.com/v2/\": x509: certificate is not valid for any names, but wanted to match noimage.com. Error: ErrImagePull. Error: ImagePullBackOff",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": "",
            "involvedObject": {
                "kind": "Pod",
                "namespace": "default",
                "name": "no-image-deployment-849c4c4958-rxqmt",
                "apiVersion": "v1"
            }
        },
```

**Comment by DexterYan** [comment]
> Possible idea: for pods in a crash loop, expose the exit code of the container that ended?

good idea, I have added exit code if the pod is in crash loop without a terminated message.

**Review by CpuID — APPROVED** [review]
LGTM - I haven't run it myself to play with it, but I've given the tests a good review and they look comprehensive enough and they are passing, so I'm going to trust them :)

**Pull request merged**
