### PR TITLE
Check if user has access to namespace resources before collecting

### LINKED ISSUE #656: Support bundle takes a long time to collect cluster resources even when it has no access to most resources
Description
```
$ cat sb.yaml 
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example-support-bundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}

$ time kubectl support-bundle sb.yaml 

 Collecting support bundle ⠹ cluster-resourcessupport-bundle-2022-06-13T16_25_39.tar.gz

real    2m46.161s
user    0m5.102s
sys    0m2.070s
```

### PR DESCRIPTION
**Pull request by divolgin**

### CODE REVIEW

**Comment by marccampbell** [comment]
@divolgin are you able to provide any benchmarks on performance?

**Comment by divolgin** [comment]
@marccampbell nothing super scientific.  It went from about 2 minutes to about 1 minute on my cluster.  This excluded about 60 namespaces, and collected info from just 1.

**Review by danj-replicated — DISMISSED** [review]

**Comment by xavpaice** [comment]
relates to #656

**Review by danj-replicated — APPROVED** [review]

**Comment by danj-replicated** [comment]
I don't really have much to add but It compiles and runs fine 😅

**Pull request merged**
